### PR TITLE
Feature/debug

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
Rework the code, (including updated original file), to have a minimal working version.

### CODE REVIEW

**Comment by raamdev** [comment]
@AdrieanKhisbe I'm testing this but whenever I run `M-x slack` I get the following error:

```
url-register-auth-scheme: Cannot open load file: no such file or directory, debug
```

Any ideas?

**Comment by AdrieanKhisbe** [comment]
which version of emacs are you using?

Have you a `.slack-auth`  file?

**Comment by raamdev** [comment]
> which version of emacs are you using?

GNU Emacs 24.4.1 (x86_64-apple-darwin14.0.0, NS apple-appkit-1343.14)

> Have you a .slack-auth file?

I commented out `defconst slack-auth-file-name` and `defcustom slack-auth` and just manually set the following in `slack.el`:

```
  (setq slack-auth
       '(("TEAM" . "TOKEN")))
```

**Comment by AdrieanKhisbe** [comment]
_works on my machine_

**Comment by AdrieanKhisbe** [comment]
can you reproduce the error and give me the backtrace?

**Comment by raamdev** [comment]
@AdrieanKhisbe False alarm, sorry. I had recently updated my Homebrew packages via `brew update` and then cleaned up old packages via `brew cleanup`, and that deleted Emacs 24.4 on my system (which was still running). Restarting Emacs and loading the newly installed 24.5 fixed the issue I was having testing `slack.el`. 

When I run `M-x slack` I now successfully get a list of channels, but moving my cursor to a channel and pressing return just displays the channel ID in the status bar--is that as far as we can get so far or should I actually see the channel contents?

**Comment by AdrieanKhisbe** [comment]
that's normal, so far that's what implemented.
The remaining will be for another version :)

**Comment by raamdev** [comment]
@AdrieanKhisbe Great! Merged. Thank you. :-)

**Pull request merged**
